### ISSUE TITLE
https example throws error

### ISSUE THREAD

**Issue by GerryOnGithub** [chimurai/http-proxy-middleware#377] opened 2019-12-10 03:34 UTC
### Steps to reproduce

1) Goto https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/https.md
2) Grab the basic proxy server example, save to file
3) npm install http-proxy-middleware --save
4) run the example

### Expected behavior

Script runs or something

### Actual behavior

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node/node_modules/http-proxy-middleware/dist/context-matcher.js:5:20)

**Comment by chimurai** [comment] 2019-12-11 19:40
Not sure from your description how your proxy from the recipe is used in a server...
Recipe only show the proxy configuration.

You can look in de `examples` folder for working examples. Here is one for `express`
https://github.com/chimurai/http-proxy-middleware/blob/master/examples/express/index.js

**Comment by bradwbradw** [comment] 2020-07-05 08:54
The example you linked has the same problem.  The script just doesn't run.  I think it's a dependency issue with micromatch

```

/.../node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/.../node_modules/http-proxy-middleware/dist/context-matcher.js:5:20)

npm ERR! Darwin 17.7.0
npm ERR! argv "/[...]/versions/node/v6.17.1/bin/node" "/[...]/versions/node/v6.17.1/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

**Comment by chimurai** [comment] 2020-07-05 15:52
Looks like you're using node 6, which is not supported anymore.

**Comment by bradwbradw** [comment] 2020-07-05 20:35
I tried again with node 12 and got the same result

**Comment by chimurai** [comment] 2020-07-05 22:31
Can you create a minimal reproducible example?

**Comment by bradwbradw** [comment] 2020-07-06 19:30
My mistake! I did not `rm -r node_modules` and reinstall after I switched to node 12 using `nvm`.

Http example works fine

**Comment by chimurai** [comment] 2020-07-06 21:33
Good the hear you've found the issue.

Closing issue since as original post had the same issue with the spread operator:`SyntaxError: Unexpected token ...`

**Closed by chimurai** 2020-07-06 21:33 UTC
Labels: need minimal example
