### ISSUE TITLE
proxy('**/*.do', {...})  throw exception SyntaxError: Invalid regular expression: /**/*.do/: Nothing to repeat

### ISSUE THREAD

**Issue by 029ye** [chimurai/http-proxy-middleware#392] opened 2020-02-08 01:46 UTC
set  proxy('**/*.do', {...}) ,
 throw exception  :SyntaxError: Invalid regular expression: /**/*.do/: Nothing to repeat

**Comment by chimurai** [comment] 2020-02-23 13:33
Please provide a minimal example

**Comment by chenxxzhe** [comment] 2020-03-03 14:34
me too.
![image](https://user-images.githubusercontent.com/9720961/75785685-19aa5d00-5d9f-11ea-9121-0f01e46a5027.png)

**Comment by chenxxzhe** [comment] 2020-03-03 14:41
"http-proxy-middleware": "^1.0.1",
"@vue/cli-service": "^3.8.0",

**Comment by chenxxzhe** [comment] 2020-03-03 14:42
```js
devServer: {
    proxy: {
      '**/*.zip': {
        target,
        changeOrigin: true,
        ws: false
      }
    }
  },
```

**Comment by chimurai** [comment] 2021-03-30 21:54
Unable to reproduce. Closing issue.

Feel free to reopen when minimal working example can be provided

**Closed by chimurai** 2021-03-30 21:54 UTC
Labels: need minimal example
