### ISSUE TITLE
Proxying Websockets Error "Invalid WebSocket frame: RSV1 must be clear"

### ISSUE THREAD

**Issue by jira-zz** [chimurai/http-proxy-middleware#799] opened 2022-07-11 17:17 UTC
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

In console infinite line of 
```
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
```
is displayed.

Connecting to the ws url I'm getting `Error: Invalid WebSocket frame: RSV1 must be clear`

### Step-by-step reproduction instructions

```shell
1)Create simple Websocket server - https://gist.github.com/jira-zz/ebefc82d0f683a11695bcfa5415ff5ba
2) Create stock create-react-app
3) Add setupProxy.js to src - https://gist.github.com/jira-zz/ebefc82d0f683a11695bcfa5415ff5ba
4) start sever created in 1)
5) start react app using npm start
```

### Expected behavior (be clear and concise)

It should proxy Websockets

### How is http-proxy-middleware used in your project?

```shell
├── http-proxy-middleware@2.0.6
└─┬ react-scripts@5.0.1
  └─┬ webpack-dev-server@4.9.3
    └── http-proxy-middleware@2.0.6 deduped
```

### What http-proxy-middleware configuration are you using?

```typescript
const { createProxyMiddleware } = require('http-proxy-middleware');


module.exports = function (app) {
    const appProxy = createProxyMiddleware('/ws', {
        target: 'http://localhost:5000',
        ws: true
    });

    app.use(appProxy);
};
```

### What OS/version and node/version are you seeing the problem?

```shell
Ubuntu 22.04 LTS in WSL2
node v18.5.0
```

**Comment by chimurai** [comment] 2022-07-11 18:12
dupe of #209

To keep the issue/discussion central.

**Closed by chimurai** 2022-07-11 18:12 UTC
