### ISSUE TITLE
Add support to multiple targets per proxy.

### ISSUE THREAD

**Issue by patrickelectric** [chimurai/http-proxy-middleware#748] opened 2022-04-14 13:11 UTC
### Describe the feature you'd love to see

I have a proxy that is configured like this:
```
proxy: {
      '^/status': {
        target: http://potato.local/,
      },
```
But sometimes the connection is done via wifi, or bluetooth and the mdns interface name may change.
```
proxy: {
      '^/status': {
        target: [
                http://potato.local/,
                http://potato-wifi.local/,
                http://potato-bluetooth.local/,
        ]
      },
```

### Additional context (optional)

Since the endpoint may change, it would help for target to be a list.

**Comment by chimurai** [comment] 2022-04-14 14:10
Duplicate of https://github.com/chimurai/http-proxy-middleware/issues/367

You can use the `router` property to specify multiple targets or a dynamic target.

**Closed as completed by chimurai** 2022-04-14 14:10 UTC

**Comment by Azbesciak** [comment] 2025-02-23 14:30
@chimurai 
Not sure what was the purpose of the ticket's creator, but I would like to also have multiple targets for a given source endpoint - as a broadcast.
Currently I see the following definition for `router`
```
 router?: {
        [hostOrPath: string]: httpProxy.ServerOptions['target'];
    } | ((req: Request) => httpProxy.ServerOptions['target']) | ((req: Request) => Promise<httpProxy.ServerOptions['target']>);
    
```
Which means I can have only one target for a given path. Whereas I would like to send the same request to multiple targets at the same time

**Comment by chimurai** [comment] 2025-02-23 20:33
The `router` option allows to modify the target per request.

@Azbesciak proxying 1 source to multiple targets is beyond the scope of `http-proxy-middleware`, since it just uses the `target` from `http-proxy`.
